name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/api.tsquarecenter.com
            php artisan down --message="جاري التحديث..." --retry=60
            git pull origin main
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan migrate --force --step
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
            php artisan cache:clear
            php artisan storage:link
            composer dump-autoload --optimize
            pm2 restart tsquare-queue tsquare-scheduler
            sudo systemctl reload php-fpm-83
            php artisan up
